исправлена команда gift
tarakania/discord-bot pull request #4
Opened 2019-09-04 12:34 UTC by MKokyn

2019-09-04 13:58 UTC, Fogapod requested changes

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/commands/rpg/inventory/gift.py
> +        f"Вы действительно хотите передать **{item}** в количестве **{str(count)}** персонажу **{player2}**?"
str() не нужен

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/commands/rpg/inventory/gift.yaml
> +    type: int
type: string

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/commands/rpg/inventory/gift.yaml
> +    type: int
default: 1

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +            counts[item1] = counts.get(item1, 0) + 1
```python
count = 0
for i in self._items:
  if i == item:
    count += 1
```

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        if isinstance(item, int):
Зачем повторная проверка?

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        print("f")
Убрать

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        print("q")
Убрать

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        self, item: Item, pool: asyncpg.Pool, count: int
count: int = 1

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        self, item: Item, player: Player, pool: asyncpg.Pool, count: int
count: int = 1

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        await pool.fetch(
Вынести в отдельную функцию

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        await pool.fetch(
Вынести в отдельную функцию

2019-09-04 13:58 UTC, Fogapod commented on tarakania_rpg/commands/rpg/inventory/gift.py
> +            count = int(args[2])
Не ловится ошибка преобразования в int

2019-09-08 10:05 UTC, Fogapod requested changes

2019-09-08 10:05 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> -
Почему убран отступ?

2019-09-08 10:05 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +
Функция должна называться add_item

2019-09-08 10:05 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        if item not in self.inventory:
Функция должна называться remove_item

2019-09-08 10:05 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +
Почему удаление до проверки наличия предмета в инвентаре?

2019-09-08 10:05 UTC, Fogapod commented on tarakania_rpg/commands/rpg/inventory/gift.py
>      if len(args) == 2:
Длина всегда будет 3, так как добавлено значение аргумента по умолчанию

2019-09-11 11:55 UTC, Fogapod requested changes

2019-09-11 11:55 UTC, Fogapod commented on tarakania_rpg/commands/rpg/inventory/gift.py
> +                return "Значение count не может быть минусовым"
Количество должно быть больше нуля

2019-09-11 11:55 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        await self._write_items(player, pool)
Функция не должна вызывать _write_items

2019-09-11 11:55 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        await self._write_items(player, pool)
Функция не должна вызывать _write_items

2019-09-11 11:55 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        return await self.inventory._remove_item(item, self, pool, count)
Должна вызываться remove

2019-09-11 11:55 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        return await self.inventory._add_item(item, self, pool, count)
Должна вызываться add

2019-09-16 11:36 UTC, Fogapod requested changes

2019-09-16 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        await self.inventory._write_items(self, pool)
self.inventory._write_items не должно вызываться здесь

2019-09-16 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        await self.inventory._write_items(self, pool)
self.inventory._write_items не должно вызываться здесь

2019-09-18 11:36 UTC, Fogapod requested changes

2019-09-18 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> -        if item not in self:
нет проверки наличия предмета в инвентаре

2019-09-18 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +            self._items.remove(i)
нет проверки наличия предмета в инвентаре

2019-09-18 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        self, item: List[Item], player: Player, pool: asyncpg.Pool
переменная должна называться `items`

2019-09-18 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        self, item: List[Item], player: Player, pool: asyncpg.Pool
переменная должна называться `items`

2019-09-18 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        return item[0]
почему `item[0]` ?

2019-09-18 11:36 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        return item[0]
почему `item[0]` ?

2019-09-18 11:47 UTC, MKokyn commented on tarakania_rpg/rpg/player.py
> +        return item[0]
pre-commit  выдал ошибку, `Incompatible return value type (got "List[Item]", expected `"Item")`, использовал item[0]

2019-09-19 06:41 UTC, Fogapod requested changes

2019-09-19 06:41 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        if item not in self:
Зачем проверка в add?

2019-09-19 06:41 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +        for item in items:
Зачем проверка в add_many?

2019-09-20 09:33 UTC, Fogapod requested changes

2019-09-20 09:33 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
> +    def get_count(self, item: Item) -> int:
`return self._items.count(item)`

2019-09-20 09:33 UTC, Fogapod commented on tarakania_rpg/rpg/player.py
>              # prefer removing item from inventory
Не обрабатывается удаление нескольких вещей, если вещь экипирована

2019-09-24 11:20 UTC, merged